[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
parking_lot = "0.12.1"
rocket = { version = "=0.5.0-rc.3", features = ["json"] }
tokio = { version = "1.20", features = ["macros", "rt-multi-thread"] }
